# Generated by Django 5.0.4 on 2024-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
