# Generated by Django 5.0.4 on 2024-04-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_movie_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
